# Generated by Django 4.2.11 on 2024-03-25 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
